myproject/urls.py
from django.contrib import admin
from django.urls import path
from submissions.views import my_view, get_result_by_request_id

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('submit/', include('submissions.urls')),
    # path('', redirect_to_submit, name='home'),
    # path('result/<str:request_id>', get_result_by_request_id, name='get_result_by_request_id'),
    # path('submit/<str:request_id>', render_submission_page, name='render_submission_page'),
    path('api/my-endpoint/', my_view, name='my-endpoint'),
    path('api/result/<str:request_id>', get_result_by_request_id, name='get_result_by_request_id')
]

submissions/urls.py
# from django.urls import path
# from .views import submit_code, success, send_code

# urlpatterns = [
#     path('', submit_code, name='submit_code'),
#     path('success/', success, name='success'),
#     path('send_code/', send_code, name='send_code'),
# ]

submissions/models.py
from django.db import models
import uuid

class Submission(models.Model):
    request_id = models.CharField(max_length=100, unique=True, default=uuid.uuid4().hex)
    code = models.TextField()
    language = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if not self.request_id:
            self.request_id = str(uuid.uuid4())
            # self.request_id = '2'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.language
    
class CodeResult(models.Model):
    request_id = models.CharField(max_length=100, unique=True)
    result = models.TextField()

    def __str__(self):
        return self.request_id

submissions/forms.py
from django import forms
from .models import Submission

class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ['code', 'language', 'request_id']

submissions/views.py
from django.shortcuts import render
from .forms import SubmissionForm
from django.http import HttpResponseRedirect, JsonResponse
import pika
import myproject.settings as settings
import json
from .models import CodeResult, Submission
from django.views.decorators.csrf import csrf_exempt

# def submit_code(request):
#     if request.method == 'POST':
#         form = SubmissionForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return JsonResponse({'success': True, 'message': '코드가 성공적으로 제출되었습니다!'})
#     else:
#         form = SubmissionForm()
#     return render(request, 'submissions/submit_code.html', {'form': form})

# def success(request):
#     return render(request, 'submissions/success.html')

# def redirect_to_submit(request):
#     return HttpResponseRedirect('/submit/')

def send_to_rabbitmq(request_id, code, language):
    connection = pika.BlockingConnection(
        pika.ConnectionParameters(host=settings.RABBITMQ_HOST,
            port=5672,
            credentials=pika.PlainCredentials('rabbitmq username ss', 'rabbitmq password ss')
        )
    )
    channel = connection.channel()

    channel.queue_declare(queue=settings.RABBITMQ_QUEUE_NAME)

    message = {
        'request_id': request_id,
        'code': code,
        'language': language,
    }
    channel.basic_publish(
        exchange='',
        routing_key=settings.RABBITMQ_QUEUE_NAME,
        body=json.dumps(message)
    )
    connection.close()

# def send_code(request):
#     if request.method == 'POST':
#         form = SubmissionForm(request.POST)
#         if form.is_valid():
#             submission = form.save(commit=False)
#             # request_id = str(uuid.uuid4())
#             # # request_id = '2'
#             # submission.request_id = request_id
#             submission.save()

#             request_id = form.cleaned_data['id']
#             code = form.cleaned_data['code']
#             language = form.cleaned_data['language']

#             send_to_rabbitmq(request_id=request_id, code=code, language=language)

#             return JsonResponse({'success': True, 'message': '코드가 성공적으로 제출되었습니다!', 'request_id': request_id})
#     else:
#         form = SubmissionForm()
#     return render(request, 'submissions/submit_code.html', {'form': form})

def get_result_by_request_id(request, request_id):
    try:
        result = CodeResult.objects.get(request_id=request_id)
        data = {
            'request_id': result.request_id,
            'result': result.result,
        }
        return JsonResponse(data=data)
    except CodeResult.DoesNotExist:
        return JsonResponse({"error": "Result not found"}, status=404)

# def render_submission_page(request, request_id):
#     form = SubmissionForm()
#     return render(request, 'submissions/submit_code.html', {'form': form, 'request_id': request_id})

@csrf_exempt
def my_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        code = data.get('code', '')
        id = data.get('id', '')
        language = data.get('language', '')
        
        snippet = Submission.objects.create(request_id=id, language=language, code=code)
        send_to_rabbitmq(request_id=id, code=code, language=language)

        return JsonResponse({'message': f'You sent: {code}'}, status=200)
    return JsonResponse({'error': 'Invalid request'}, status=400)

submissions/templates/submissions/index.html
<!-- <table class="table-contents" style="padding: 10px;">
    <tr>
        <th>title</th>
        <th>contents</th>
    </tr>
    {% for post in posts %}
    <tr>
        <td>{{post.post_title}}</td>
        <td>{{post.post_content}}</td>
    </tr>
    {%endfor%}
</table> -->

<!-- 사용 안 하는 파일 -->

submissions/templates/submissions/submit_code.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Online Code Editor</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            var request_id = '{{ request_id|default:"" }}';
            
            function checkResult() {
                if (request_id) {
                    $.ajax({
                        type: 'GET',
                        url: '/result/' + request_id,
                        success: function(response) {
                            if (response.result) {
                                $('#real_result').html(response.result);
                                clearInterval(interval); // Stop checking once the result is found
                            }
                        },
                        error: function(response) {
                            if (response.responseJSON.error === 'Result not found') {
                                console.log('Result not ready yet, retrying...');
                                $('#real_result').html('Result not ready yet, retrying...');
                            } else {
                                alert('Error: ' + response.responseJSON.error);
                                clearInterval(interval); // Stop checking on error
                            }
                        }
                    });
                }
            }

            $('form').on('submit', function(event) {
                event.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: 'send_code/',
                    data: $(this).serialize(),
                    success: function(response) {
                        if (response.success) {
                            alert(response.message);
                            request_id = response.request_id;
                            interval = setInterval(checkResult, 1000); // Start checking every 5 seconds
                        } else {
                            alert('Submission failed. Please try again.');
                        }
                    }
                });
            });

            if (request_id) {
                interval = setInterval(checkResult, 1000); // Start checking every 1 seconds if request_id is present
            }
        });
    </script>
    <style>
        #temp {
            display: flex;
        }
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f9;
            padding: 20px;
        }
        form, #result {
            flex: 1;
            background: white;
            padding: 20px;
            margin: 10px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .form-field {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input, textarea, select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box;
        }
        #id_code {
            height: 300px;
        }
        button {
            background-color: #5c67f2;
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            cursor: pointer;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <h1>온라인 코드 편집기</h1>
    <div id="temp">
        <form method="post">
            <div class="form-field">
                <label for="id_code">코드:</label>
                <textarea id="id_code" name="code" required></textarea>
            </div>
            <div class="form-field">
                {% csrf_token %}
                <label for="id_language">언어 선택:</label>
                <select id="id_language" name="language">
                    <option value="python">Python</option>
                    <option value="javascript">JavaScript</option>
                    <option value="java">Java</option>
                    <option value="csharp">C#</option>
                    <option value="go">Go</option>
                </select>
            </div>
            <button type="submit">제출</button>
        </form>
        <div id="result">결과:
            <div id="real_result"></div>
        </div>
    </div>
</body>
</html>

submissions/templates/submissions/success.html
<!-- <!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>성공</title>
</head>
<body>
    <p>코드가 성공적으로 제출되었습니다!</p>
</body>
</html> -->

<!-- 사용 안 하는 파일 -->